import react from '@vitejs/plugin-react';
import { fileURLToPath } from 'node:url';
import { defineConfig } from 'vitest/config';

export default defineConfig({
  plugins: [react()],
  test: {
    environment: 'jsdom',
    globals: true,
    setupFiles: ['./vitest.setup.ts'],
    include: ['src/**/*.test.{ts,tsx}'],

    /**
     * Coverage baseline (tasks/15-quality-gates.md).
     *
     * Scoped to the layers that hold logic worth asserting. `src/app/**` is excluded because App
     * Router files are route declarations and server component shells — importing one to raise a
     * percentage proves the module parses, not that anything works. `src/generated/**` is machine
     * output regenerated by `npm run codegen`.
     *
     * Thresholds are measured, not aspirational: see docs/QUALITY-GATES.md for the figures at the
     * time task 15 landed and the process for raising them. They ratchet up, never down.
     */
    coverage: {
      provider: 'v8',
      reporter: ['text-summary', 'json-summary', 'html', 'lcov'],
      reportsDirectory: './coverage',
      include: ['src/components/**', 'src/features/**', 'src/hooks/**', 'src/lib/**'],
      exclude: [
        'src/generated/**',
        'src/test/**',
        '**/*.test.{ts,tsx}',
        '**/*.d.ts',
        // Barrel files re-export and hold no behaviour; counting them rewards adding exports.
        '**/index.ts',
      ],
      /**
       * Measured when task 15 landed, across 226 tests in 15 files:
       *   statements 35.85% (1294/3609) · branches 77.53% (252/325)
       *   functions  59.16% (113/191)   · lines    35.85% (1294/3609)
       *
       * Statement coverage is low and the threshold is honest about that rather than flattering:
       * most of src/components and src/features is presentational markup with no test. Branch
       * coverage is high because the logic that DOES have branches — API error mapping, auth
       * state, form validation — is well covered. Setting one blended number would hide both facts.
       *
       * These ratchet up, never down (task 15: "Do not weaken gates merely to make generated code
       * pass"). docs/QUALITY-GATES.md holds the process for changing them.
       */
      thresholds: {
        statements: 35,
        lines: 35,
        functions: 55,
        branches: 70,
      },
    },
  },
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },
});
