package com.travelplanner.application.mail;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import com.travelplanner.domain.valueobject.MailMessage;
import java.util.Map;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.EnumSource;

/**
 * The template boundary. Two things are worth pinning here, and both are the kind of defect nobody
 * notices until a user does not receive a link.
 *
 * <p><b>Every template exists and every placeholder resolves.</b> A missing file or a renamed
 * placeholder is caught by the build rather than by a silent {@code mail_failed} in production.
 *
 * <p><b>User-supplied values are escaped in HTML.</b> The username is echoed into a mail sent to a
 * third party, so an unescaped value is script injection into somebody else's inbox.
 */
class MailTemplateRendererTest {

    /**
     * Every placeholder any template uses. Rendering each template against this superset proves the
     * files parse and resolve; {@code AccountMailService} is what proves each call site supplies the
     * right subset, and its tests exercise that path.
     */
    private static final Map<String, String> FULL_MODEL = Map.of(
            "username", "aisyah",
            "app_url", "https://app.example.test",
            "verify_link", "https://app.example.test/verify-email?token=abc",
            "reset_link", "https://app.example.test/reset-password?token=abc",
            "forgot_url", "https://app.example.test/forgot-password",
            "sign_in_url", "https://app.example.test/sign-in",
            "sign_up_url", "https://app.example.test/sign-up",
            "providers", "FIREBASE_GOOGLE");

    private final MailTemplateRenderer renderer = new MailTemplateRenderer();

    @ParameterizedTest
    @EnumSource(MailTemplate.class)
    void rendersBothBodiesForEveryRegisteredTemplate(MailTemplate template) {
        MailMessage message = renderer.render(template, "aisyah@example.com", FULL_MODEL);

        assertThat(message.subject()).isEqualTo(template.subject());
        assertThat(message.to()).isEqualTo("aisyah@example.com");
        // Both parts are required. A text alternative generated by stripping tags is what users
        // are routinely told not to trust, and some gateways deliver nothing else.
        assertThat(message.htmlBody()).contains("<");
        assertThat(message.textBody()).doesNotContain("<div").doesNotContain("{{");
    }

    @ParameterizedTest
    @EnumSource(MailTemplate.class)
    void leavesNoPlaceholderUnresolvedInEitherBody(MailTemplate template) {
        MailMessage message = renderer.render(template, "aisyah@example.com", FULL_MODEL);

        assertThat(message.htmlBody()).doesNotContain("{{").doesNotContain("}}");
        assertThat(message.textBody()).doesNotContain("{{").doesNotContain("}}");
    }

    @Test
    void escapesUserSuppliedValuesInHtmlButNotInText() {
        Map<String, String> model = new java.util.HashMap<>(FULL_MODEL);
        model.put("username", "<img src=x onerror=alert(1)>");

        MailMessage message = renderer.render(MailTemplate.USERNAME_TAKEN, "a@example.com", model);

        assertThat(message.htmlBody())
                .doesNotContain("<img")
                .contains("&lt;img src=x onerror=alert(1)&gt;");
        // Plain text has no markup to break out of, and escaping it would show the reader
        // "&lt;img" where they typed "<img".
        assertThat(message.textBody()).contains("<img src=x onerror=alert(1)>");
    }

    @Test
    void failsLoudlyWhenAPlaceholderHasNoValue() {
        // A silent skip would put "{{reset_link}}" in somebody's inbox; MailDispatcher turns this
        // into a logged mail_failed, which is visible.
        assertThatThrownBy(() ->
                renderer.render(MailTemplate.RESET_PASSWORD, "a@example.com", Map.of()))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("reset_link");
    }

    @Test
    void keepsTheRecipientOutOfAMessagesOwnStringRepresentation() {
        // MailMessage is the one object holding both an address and the body of a message about
        // that person's account, so its default rendering must be safe to log by accident.
        MailMessage message = renderer.render(MailTemplate.WELCOME, "aisyah@example.com", FULL_MODEL);

        assertThat(message.toString()).doesNotContain("aisyah@example.com").contains("***");
    }
}
