/**
 * `npm run task:context -- 21` — the execution pack for one task (review §6.A).
 *
 * The finding this answers: an agent starting a task reads thousands of lines of planning documents
 * to establish a handful of facts, and pays for all of it again on the next task. The facts are
 * cheap to compute and the documents are not, so they are computed here.
 *
 * What the pack is *for* is as important as what it contains. It is not a substitute for reading the
 * task brief — the brief is quoted in full where it matters, and linked where it does not. It is a
 * substitute for the search that precedes the reading: which dependencies are actually `done`, which
 * migration number is free, which port already exists, which findings are open against this task,
 * and where in a 3,700-line PLAN the two relevant sections are.
 *
 * Everything is derived. Nothing in this file is a fact somebody has to remember to update, which is
 * the only property that makes a generated document worth trusting six weeks from now.
 *
 * Prints to stdout by default so it can be piped or pasted; `--out <file>` writes it instead.
 */

import { writeFileSync } from 'node:fs';
import { buildCodeMap } from './lib/code-map.mjs';
import {
  formatBytes,
  markdownSections,
  normaliseTaskId,
  parseStatusLedger,
  readText,
  readTextIfPresent,
  repoPath,
  taskFile,
} from './lib/repo.mjs';

/** The brief headings quoted verbatim, in the order the pack numbers them. */
const BRIEF_HEADINGS = ['Objective', 'Scope', 'Do not', 'Definition of Done'];

const args = process.argv.slice(2);
const taskId = normaliseTaskId(args.find((arg) => !arg.startsWith('--')));
const outIndex = args.indexOf('--out');
const outFile = outIndex === -1 ? null : args[outIndex + 1];

if (taskId === null) {
  console.error('Usage: npm run task:context -- <task id>      e.g. npm run task:context -- 21');
  process.exit(2);
}

const brief = taskFile(taskId);
if (brief === null) {
  console.error(`task:context: no tasks/${taskId}-*.md brief exists.`);
  process.exit(2);
}

const pack = renderPack(taskId, brief);

if (outFile === null) {
  process.stdout.write(pack);
} else {
  writeFileSync(outFile, pack, 'utf8');
  console.log(`task:context: wrote ${outFile} (${formatBytes(Buffer.byteLength(pack))}).`);
}

function renderPack(id, briefPath) {
  const map = buildCodeMap();
  const ledger = parseStatusLedger();
  const byId = new Map(ledger.map((row) => [row.id, row]));
  const row = byId.get(id);
  const sections = markdownSections(readText(briefPath));
  const task = map.tasks[id];

  return [
    `# Task ${id} context pack — ${task.title}`,
    '',
    'Generated by `npm run task:context -- ' + id + '`. Every value below is derived from the tree at',
    'this commit; none of it is hand-maintained. Read the brief itself for anything not quoted here:',
    `\`${task.file}\`.`,
    '',
    renderGate(id, row, byId),
    renderBriefSection('Objective', sections),
    renderBriefSection('Scope', sections),
    renderBriefSection('Do not', sections),
    renderBriefSection('Definition of Done', sections),
    renderRequiredReading(sections),
    renderExtensionPoints(map),
    renderMigrations(map),
    renderOpenFindings(row, ledger),
    renderPreviousHandoff(id),
    renderCommands(),
  ]
    .filter((block) => block !== null)
    .join('\n');
}

/**
 * The dependency gate, computed rather than asserted.
 *
 * Review finding #8: tasks 18, 19 and 20 each started while a dependency was still `in_progress`,
 * and in every case the reason was defensible — the *capability* being depended on existed even
 * though the task did not. The verdict below therefore names both facts and refuses to editorialise:
 * it says which dependencies are open, and it says that starting anyway needs a recorded capability
 * gate. An agent that sees "BLOCKED" with no explanation invents one.
 */
function renderGate(id, row, byId) {
  const dependencies = row?.dependsOn ?? [];
  const lines = [
    '## 1. Gate',
    '',
    `- **Ledger status:** \`${row?.status ?? 'unknown'}\``,
    `- **Depends on:** ${dependencies.length === 0 ? '—' : dependencies.join(', ')}`,
    '',
  ];

  if (dependencies.length > 0) {
    lines.push('| Dependency | Title | Status |', '|---|---|---|');
    for (const dependency of dependencies) {
      const target = byId.get(dependency);
      lines.push(`| ${dependency} | ${target?.title ?? '(not in ledger)'} | \`${target?.status ?? 'unknown'}\` |`);
    }
    lines.push('');
  }

  // `done_with_accepted_debt` is merged + gated with an owned follow-up (STATUS.md status values).
  // Dependents may proceed; the debt task owns closing the named F-NN.
  const open = dependencies.filter((dependency) => {
    const status = byId.get(dependency)?.status;
    return status !== 'done' && status !== 'done_with_accepted_debt';
  });
  if (open.length === 0) {
    lines.push(
      '**Verdict: clear.** Every dependency is `done` or `done_with_accepted_debt`.',
      '',
    );
  } else {
    lines.push(
      `**Verdict: blocked by ${open.join(', ')}.** \`docs/AGENT-HARNESS.md\` §2 requires every`,
      'dependency to be `done` before a task starts. If the specific *capability* this task needs is',
      'already finished inside an `in_progress` dependency, that is a real situation and the answer is',
      'to record a capability gate in `tasks/STATUS.md` — not to start and explain afterwards, which is',
      'what happened to tasks 18, 19 and 20.',
      '',
    );
  }
  return lines.join('\n');
}

function renderBriefSection(heading, sections) {
  const body = sections.get(heading);
  if (body === undefined || body === '') {
    return null;
  }
  const position = BRIEF_HEADINGS.indexOf(heading) + 2;
  return [`## ${position}. ${heading}`, '', body, ''].join('\n');
}

/**
 * "Required reading", with every `§` reference resolved to a line range.
 *
 * Review §6.H: a brief that says "PLAN §3.2" is asking an agent to search a 3,700-line file, and the
 * cheapest correct behaviour for a model that cannot find the anchor is to read the whole thing. A
 * line range turns that into one bounded read.
 *
 * An unresolvable reference is printed as unresolved rather than omitted. Silently dropping it would
 * hide the two cases that matter: a section that was renumbered, and a typo.
 */
function renderRequiredReading(sections) {
  const body = sections.get('Required reading');
  if (body === undefined || body === '') {
    return null;
  }
  const lines = ['## 6. Required reading, resolved', ''];

  for (const line of body.split('\n')) {
    const source = /`([^`]+\.(?:md|yaml|yml))`/.exec(line);
    if (source === null) {
      lines.push(line);
      continue;
    }
    const references = [...line.matchAll(/§\s*([\d.]+[a-z]?)/g)].map((match) => match[1]);
    if (references.length === 0) {
      lines.push(line);
      continue;
    }
    const resolved = references.map((reference) => locateSection(source[1], reference));
    lines.push(`${line}`, `  - ${resolved.join('; ')}`);
  }
  lines.push('');
  return lines.join('\n');
}

/**
 * Finds `§4.0.2` in a markdown file by matching a heading whose text starts with that number.
 *
 * The end of the range is the next heading at the same level or shallower, which is what makes the
 * range a section rather than "everything to the end of the file".
 */
function locateSection(relativePath, sectionNumber) {
  const text = readTextIfPresent(repoPath(...relativePath.split('/')));
  if (text === null) {
    return `§${sectionNumber} — **file not found**: \`${relativePath}\``;
  }
  const lines = text.split('\n');
  const escaped = sectionNumber.replace(/\./g, '\\.');
  const headingAt = lines.findIndex((line) => new RegExp(`^(#{2,6})\\s+§?${escaped}[.\\s]`).test(line));
  if (headingAt === -1) {
    return `§${sectionNumber} — **not found** (renumbered, or a typo)`;
  }
  const level = /^(#+)/.exec(lines[headingAt])[1].length;
  let end = lines.length;
  for (let index = headingAt + 1; index < lines.length; index += 1) {
    const next = /^(#+)\s/.exec(lines[index]);
    if (next !== null && next[1].length <= level) {
      end = index;
      break;
    }
  }
  return `§${sectionNumber} → \`${relativePath}\` lines ${headingAt + 1}–${end}`;
}

/**
 * The extension points that already exist, so a task extends rather than re-creates.
 *
 * Ports with no implementation are called out first. That combination means one of two things — a
 * port a task is expected to implement, or a port whose adapter was forgotten — and both are things
 * an agent should see before it writes a line.
 */
function renderExtensionPoints(map) {
  const unimplemented = Object.entries(map.ports)
    .filter(([, port]) => port.implementations.length === 0)
    .map(([name]) => name);
  const untranslated = Object.entries(map.errorCodes.codes)
    .filter(([, code]) => code.translated.length === 0)
    .map(([wire]) => wire);

  return [
    '## 7. Extension points that already exist',
    '',
    `Full index: \`docs/generated/CODE-MAP.json\` (regenerate with \`npm run code-map\`).`,
    '',
    `- **Ports:** ${Object.keys(map.ports).length} declared in \`domain/port/\`.`,
    unimplemented.length === 0
      ? '  Every one has at least one implementation.'
      : `  **No implementation yet:** ${unimplemented.join(', ')}.`,
    `- **Error codes:** ${Object.keys(map.errorCodes.codes).length} registered in \`api/error/ApiErrorCode.java\`.`,
    untranslated.length === 0
      ? '  Every one is translated in `apps/frontend/src/locales/`.'
      : `  **Untranslated — would reach a user as a raw identifier:** ${untranslated.join(', ')}.`,
    `- **Frontend query-key namespaces:** ${map.features.frontendQueryKeys.namespaces.join(', ')}.`,
    `- **Frontend features:** ${Object.keys(map.features.frontendFeatures).join(', ')}.`,
    '',
  ].join('\n');
}

function renderMigrations(map) {
  const recent = map.migrations.applied.slice(-3);
  return [
    '## 8. Schema',
    '',
    `- **Next free migration: \`${map.migrations.nextFreeVersion}\`.** Derived from the filenames, not from a note.`,
    map.migrations.gaps.length === 0 ? '- No version gaps.' : `- **Version gaps:** ${map.migrations.gaps.join(', ')}.`,
    '- Most recent:',
    ...recent.map((migration) => `  - \`V${migration.version}\` — ${describeMigration(migration)}`),
    '',
  ].join('\n');
}

function describeMigration(migration) {
  const parts = [];
  if (migration.createsTables.length > 0) {
    parts.push(`creates ${migration.createsTables.join(', ')}`);
  }
  if (migration.altersTables.length > 0) {
    parts.push(`alters ${migration.altersTables.join(', ')}`);
  }
  return parts.length === 0 ? 'no table changes' : parts.join('; ');
}

/**
 * The `F-NN` findings this task's ledger row names, with their registered text.
 *
 * Findings are recorded in two places by design — mentioned in the row that discovered them, defined
 * in the register table — and joining the two is exactly the lookup an agent would otherwise do by
 * scrolling. A finding mentioned but never registered is reported as such: that is a real bookkeeping
 * failure, and it is invisible unless something goes looking.
 */
function renderOpenFindings(row, ledger) {
  const mentioned = [...new Set([...(row?.notes ?? '').matchAll(/F-(\d+)/g)].map((match) => match[1]))];
  if (mentioned.length === 0) {
    return null;
  }
  const register = readText(repoPath('tasks', 'STATUS.md'));
  const lines = ['## 9. Findings this task already carries', ''];

  for (const number of mentioned.sort((left, right) => Number(left) - Number(right))) {
    const entry = new RegExp(`^\\|\\s*\\*\\*F-${number}\\*\\*\\s*\\|(.*)$`, 'm').exec(register);
    if (entry === null) {
      lines.push(`- **F-${number}** — mentioned in the ledger row but **not in the findings register**.`);
      continue;
    }
    lines.push(`- **F-${number}** — ${entry[1].split('|')[0].trim()}`);
  }
  lines.push('');
  return lines.join('\n');
}

/**
 * The previous task's Handoff section.
 *
 * "Previous" means the numerically preceding brief, not a dependency. That is deliberate: the
 * handoff sections in this repository are written as a chain — each one tells the next author what
 * was left half-done — and the chain is by number.
 */
function renderPreviousHandoff(id) {
  const previous = normaliseTaskId(String(Number(id) - 1));
  const file = previous === null ? null : taskFile(previous);
  if (file === null) {
    return null;
  }
  const handoff = markdownSections(readText(file)).get('Handoff');
  if (handoff === undefined || handoff === '') {
    return null;
  }
  return ['## 10. Handoff from task ' + previous, '', handoff, ''].join('\n');
}

function renderCommands() {
  return [
    '## 11. Commands',
    '',
    '```bash',
    'npm run verify:fast            # the edit loop — changed-scope tests, lint, typecheck',
    `npm run verify:task -- ${taskId}        # before claiming the task is done`,
    'npm run verify:full            # what CI runs; needs Docker for the container suites',
    `npm run task:report -- ${taskId}        # capture real command output as evidence`,
    '```',
    '',
    'Cheap first, expensive last (review §6.C). The gates are not weakened — `verify:full` still runs',
    'everything — but a one-line fix does not have to pay for Testcontainers to find out it compiles.',
    '',
  ].join('\n');
}
